### ISSUE TITLE
Michael's Onboarding Checklist

### ISSUE THREAD

**Issue by gmyenni** [weecology/wiki#30]
#### Physical setup

- [ ] Ask Glenda to show you where your copy of the onboarding checklist is on GitHub and how to check off completed tasks.
- [ ] Request your computer. Every weecologist gets a computer for their work/educational responsibilities. Tell Glenda if you want a laptop or desktop, and whether you want a windows, mac, or linux machine. Keep in mind that this computer is university property. It's assigned to you for work/educational purposes and when you end your official association with the lab, your computer will have to stay with us.
- [ ] (Remote People Only) If you are working remotely, check out the [Remote Working Checklist](https://wiki.weecology.org/docs/lab-policy-procedures/working-remotely/) for additional steps on computer set-up and HR paperwork that applies to you.
- [ ] (Local People Only) You will need a key to Building 150. Keys for new folks come from the WEC Building Manager, Cameron Carter ([ccriderr@ufl.edu](mailto:ccriderr@ufl.edu)). Email Cameron (Cc'ing Ethan and/or Morgan, depending on who your primary supervisor is) and let him know that you're a new member of the group and ask him for a key to Building 150.

#### Get set up on Lab Communication Platforms

- [ ] Check that Glenda has set you up on the weecology spaces for:

    - [ ] GitHub
    - [ ] Slack
    - [ ] Weecology mail/calendar
    - [ ] Dropbox (if you are working on Everglades or Portal projects)
    - [ ] Drive (if you are working on Everglades or Portal projects)

- [ ] Explore Weecology’s Slack group, sign up for any relevant channels
- [ ] Go to [Slack Quick Start Guide](https://slack.com/help/articles/360059928654-How-to-use-Slack--your-quick-start-guide) to learn slack basics
- [ ] Read Weecology’s [Slack](https://wiki.weecology.org/docs/lab-policy-procedures/slack/) page
- [ ] Take the [Markdown tutorial](https://www.markdowntutorial.com/). Markdown is a way of writing text that the computer then adds formatting to (i.e. italics, bullet points, headers). We use markdown for our website, as part of GitHub communication, and to create RMarkdown files to help keep track of projects.
- [ ] Set up your weecology calendar with your class/work schedule, when you’ll be out of town etc. You can make the names of the events public or private as you wish, this is just so others can see when you’re available for scheduling purposes.

- [ ] Staff Only: Ask Glenda to set you up with a Trello account (Trello is our project management system and how Morgan and Ethan keep track of the numerous things going on in the group)
    - [ ] Watch the [introduction to trello](https://help.trello.com/article/899-getting-started-video-demo).
    - [ ] Have Ethan, Morgan, or Glenda assign you to the boards that are relevant to your work duties.

- [ ] Optional: Add other calendars to your Weecology calendar to stay informed on other events. This can be done by finding the + sign by “Other Calendars”. Commonly used calendars include “ethan”, “morgan”, “conference room”, “UF Weecology Seminars”, and [portalproject1977@gmail.com](mailto:portalproject1977@gmail.com) (the portal calendar for keeping track of when trips are occurring)
 
#### Familiarize Yourself with Lab Culture and Values
- [ ] Browse the [Lab Policy and Procedures](https://wiki.weecology.org/docs/lab-policy-procedures/)
- [ ] Read the [Way of Weecology](https://wiki.weecology.org/docs/lab-policy-procedures/way-of-weecology/)
- [ ] Read the [Lab Code of Conduct](https://wiki.weecology.org/docs/lab-policy-procedures/code-of-conduct/)
- [ ] Read the [Software Code of Conduct](https://wiki.weecology.org/docs/lab-policy-procedures/code-of-conduct-for-software/)

#### Familiarize Yourself about Lab Procedures:

- [ ] Read lab policies about [Collaborating on GitHub](https://wiki.weecology.org/docs/computers-and-programming/git-collaboration/)
- [ ] Read about our [self-assessment process](https://wiki.weecology.org/docs/lab-policy-procedures/self-assessment/)
- [ ] Read about the [Lab Meeting Overview](https://wiki.weecology.org/docs/lab-policy-procedures/lab-meetings/)
- [ ] Read the [Social Events](https://wiki.weecology.org/docs/lab-policy-procedures/social-events/) policy

#### Explore and Get to Know Folks

- [ ] Look at the Personnel Page on the Weecology website. Is there anyone on the active list that you haven’t met yet? Contact them and say hi. Maybe set up a videomeeting or a coffee/tea/water break to chat.
- [ ] Browse the [Lab-Wiki](https://wiki.weecology.org) and read through the sidebar. Read at least one page not linked to in the onboarding guide

#### Set Up Your Computer

- [ ] Choose R and/or Python (you can always change or add the other later!). People in our groups use R and/or Python as their primary programming language. Most people use R, but if you have more serious software engineering or image processing plans in mind, talk to your advisor about Python. If in doubt, talk to your advisor or other lab members.
- [ ] For R:
    - [ ] [Download and Install R](https://cran.rstudio.com/). Site includes a windows, linux, and MacOS version. Windows users: you want the base install
    - [ ] Download and Install [RStudio](https://rstudio.com/products/rstudio/download/#download). This is the Individual Development Environment (IDE) that we use for writing R code. Choose the free version.
    - [ ] Search the [lab wiki](https://wiki.weecology.org) for R tips and tricks.

- [ ] For Python:
    - [ ] Download and Install the [Anaconda Scientific Python Distribution](https://www.anaconda.com/products/individual)
    - [ ] Download and Install [Visual Studio Code](https://code.visualstudio.com/download) This is the Integrated Development Environment that we recommend for writing Python code. Windows users: choose ‘user installer’ and 64 bit.
    - [ ] Search the [lab wiki](https://wiki.weecology.org) for Python tips and tricks.
- [ ] Install Git. Regardless of programming language you chose, do this. Git is the version control system we use for software and allows you to move things from your computer to GitHub. Follow the instructions on [Ethan’s course page](http://datacarpentry.org/semester-biology/computer-setup/) under the section “Git”. It has instructions for all three operating systems.
- [ ] Set up the link between your IDE and GitHub
    - [ ] [RStudio user instructions](https://github.com/weecology/lab-wiki/wiki/Programming:-RStudio-and-GitHub-integration)
    - [ ] Visual Studio Code Users: Talk to Henry!
- [ ] [Install Zotero](https://www.zotero.org/download/). This is the [reference manager](https://www.aje.com/arc/reference-manager-software-what-it-and-what-can-it-do/) preferred in the lab. It syncs with both Google Docs and Word. And is less likely to get into nasty fights with DropBox if you keep all your PDFs there.
    - [ ] Optional: You can also install the [zotero connector](https://www.zotero.org/download/connectors) which is a browser plugin that allows you to download articles being viewed in your browser directly to your zotero library
- [ ] Set up a file back-up service. Computers die. Laptops have accidents. Hurricanes happen. You don't want to lose all your work when one of these occurs. A way to back up your files (preferably without you having to think about it) is important. Pick and install one of the following on your computer. Set up that folder as your primary work folder.
    - [ ] DropBox: is commonly used in the lab and has a [free account](https://www.dropbox.com/basic) with up to 2 GB of storage. Staff can have a free account with more storage [through UF](https://it.ufl.edu/services/dropbox-for-education).
    - [ ] OneDrive: students also have access to “unlimited” storage on UF’s [OneDrive](https://cloud.it.ufl.edu/collaboration-tools/office-365/).
- [ ] Set up your computer to print to the lab printer. The lab printer is located in room 015 and accessible from the UFL network at 10.242.89.51. You may need to [download and install drivers](https://support.hp.com/us-en/drivers/selfservice/hp-color-laserjet-pro-mfp-m478-m479-series/19202514) before adding it as a printer in order for it to function properly.
- [ ] Set up [access to the T: drive](https://github.com/weecology/lab-wiki/wiki/Accessing-the-T:-drive). This is a shared drive for the lab, and can be used to store large files associated with your project.
- [ ] If the UF VPN is not already on your computer, install the [Cisco AnyConnect VPN](https://it.ufl.edu/ict/documentation/network-infrastructure/vpn/). You'll need this to do literature searches from off campus.

Congratulations! You have gotten yourself prepared to start working with the group! You’re now ready for Stage 2 of Onboarding: Engaging with the Science and Tools.

#### Learn about the Lab Intellectual Space:

- [ ] Work through the [Weecology reading list](https://wiki.weecology.org/docs/getting-started/lab-reading-list/). (note: the reading list is still in development). For each of the subject areas read the overview paper.

    - [ ] Portal Project Overview
    - [ ] Macroecology Overview
    - [ ] Forecasting Overview
    - [ ] IDEA
 
- [ ] Pick at least two areas that are especially interesting/relevant to you. Read all the papers listed on the reading list in that topic area, or find your own to read further
- [ ] Are you funded by a grant? Ask the grant PI (probably Ethan or Morgan) for a copy to read. Don't know if you're funded on a grant? Ask Ethan, Morgan, or Glenda (she knows everything).
- [ ] On the [lab website](https://weecology.org/), find a recent paper that looks interesting to you that is by someone currently in the group
    - [ ] Read the paper
    - [ ] Set up a meeting with that person to chat about their paper

##### Learn about Git and GitHub.

- [ ] Go through the [Git for Humans](https://speakerdeck.com/alicebartlett/git-for-humans) slide show. It’s a good high-level introduction to what Git is and the jargon associated with it.
- [ ] Read [What Is GitHub? A Beginner’s Introduction to Github](https://kinsta.com/knowledgebase/what-is-github/). This will explain the relationship between Git and GitHub.
- [ ] Do a tutorial apply what you’ve just learned. Two good ones for practicing basic commands: [GitHub Tutorial](https://guides.github.com/activities/hello-world/) and/or [git and github for beginners](https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)
- [ ] Search the lab wiki for git tips and tricks

##### Apply your markdown/Github knowledge:
- [ ] Find a page on the lab wiki that has out of date info or has a tyypo (I’m sure you’ve found something!)
- [ ] Fix that page.
- [ ] Make a commit message before you save your changes
- [ ] Identify a new page the lab wiki needs or a major change to an existing page (i.e. is there info you felt would be better moved onto one page? Something that should be added to the onboarding process? A page you wish existed?).
- [ ] Create an issue in the [Lab Wiki](https://github.com/weecology/lab-wiki) Repo that explains your proposed change/addition.

### Wrap-up
Congrats! You have completed the onboarding process! Remember to keep checking on the lab wiki to see if it has information that might be useful to you. Pages that aren’t relevant to you now may become important to you in the future as your role and skills evolve!

This guide is really just designed to get you a basic foundation. Depending on your role and prior experience, you may feel like you need more in-depth guidance on something we introduced you to here. That’s ok!

Finally, the lab wiki belongs to everyone, so feel free to edit or add pages as you identify information that was useful to you. Maybe it just serves as a useful cheatsheet for you, but in reality, if you had to figure it out, someone else in the future will too. Help out a future Weecologist by writing it down!

**Comment by ethanwhite** [comment]
I'm thinking we should probably consider @M-Rickershauser's onboarded at this point. @M-Rickershauser feel free to close this (or ask me to) if you feel good to go on this end.

**Comment by M-Rickershauser** [comment]
I think so! Yes, go ahead and close it please
________________________________
